server:
  port: 8761
  servlet:
    context-path: /registry
    
spring:
  application:
    name: registry
    
eureka:
  client:
    wait-time-in-ms-when-sync-empty: 0
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

     
